name: Append Latest Commit to PR Body

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  append_commit_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full commit history

      - name: Get latest commit message
        id: get_commit
        run: |
          echo "msg=$(git log -1 --pretty=format:'%h - %s (%an)')" >> $GITHUB_OUTPUT

      - name: Append to PR body
        uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        with:
          script: |
            github.rest.pulls.update({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: context.payload.pull_request.body + '\n\n---\n### Last Commit\n`${{ steps.get_commit.outputs.msg }}`'
            })

